CREATE SEQUENCE SEQ_OS_COUNTRY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_STATE START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_CITY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_DELE START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_COLONY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_POSTAL START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_ADDRESS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_CUSTMR START WITH 1 INCREMENT BY 1 NOMAXVALUE ;