
CREATE TABLE TB_OS_ORDER
(
	ID					NUMBER(38,0) NOT NULL,
	PRODUCT_ID			NUMBER(38,0),
	QUANTITY		    NUMBER(38,0),
	ORDER_STATUS		VARCHAR2(500),
	T_AMOUNT				NUMBER(30,2),
	CRT_TS				TIMESTAMP(6),
	CRT_BY				VARCHAR2(50)
);
ALTER TABLE TB_OS_ORDER ADD CONSTRAINT OS_ORDER_PK PRIMARY KEY(ID);
