CREATE SEQUENCE SEQ_OS_CATAGORY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_INVENTORY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_PRODUCTS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
